### ISSUE TITLE
IPFIX Support

### ISSUE THREAD

**Issue by phspies** [chelaxe/NetFlow#1]
Chelaxe,

Thank you for your code on Netflow V9...

Do you know how much effort it will take to update this code to support IPFIX?

Regards

**Comment by chelaxe** [comment]
Добрый день.

Для поддержки IPFIX необходимо многие правки в коде. Я думаю - это
отдельная реализация, которой я могу заняться при соответствующей оплате.

Спасибо

2016-05-27 23:25 GMT+05:00 Phillip Spies <notifications@github.com>:

**Comment by phspies** [comment]
What will it cost?

Date: Mon, 30 May 2016 08:56:19 -0700

**Comment by chelaxe** [comment]
1 месяц разработки. Реализация классов работы с IPFIX и примера их
использования. Код должен быть свободным и размещен на GITHUB. Ценя - 150$

2016-05-31 7:09 GMT+05:00 Phillip Spies <notifications@github.com>:
